# Generated by Django 5.1.3 on 2025-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="profissao",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pessoa",
            name="salario",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
