# Generated by Django 5.1.3 on 2025-03-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoas", "0002_pessoa_profissao_pessoa_salario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="idade",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="nome",
            field=models.CharField(default="sem nome", max_length=100),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="profissao",
            field=models.CharField(default="sem profissão", max_length=100),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="salario",
            field=models.IntegerField(default=-1),
        ),
    ]
