# Generated by Django 5.1.3 on 2025-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoas", "0003_alter_pessoa_idade_alter_pessoa_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="nome",
            field=models.CharField(default="nome", max_length=100),
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="profissao",
            field=models.CharField(default="profissão", max_length=100),
        ),
    ]
