# Generated by Django 5.1.3 on 2025-03-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="nome", max_length=100)),
                ("nr_elementos", models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="nome", max_length=100)),
                ("nr_musicas", models.IntegerField(default=-1)),
                (
                    "band",
                    models.ForeignKey(
                        default="Sem banda",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="bandas.band",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="nome", max_length=100)),
                ("duration", models.IntegerField(default=-1)),
                (
                    "album",
                    models.ForeignKey(
                        default="Sem album",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="bandas.album",
                    ),
                ),
            ],
        ),
    ]
