# Generated by Django 5.1.3 on 2025-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="capa",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="album",
            name="spotify_link",
            field=models.CharField(default="link", max_length=200),
        ),
        migrations.AddField(
            model_name="band",
            name="ano_criacao",
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name="band",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="music",
            name="lyrics",
            field=models.TextField(default="letra"),
        ),
        migrations.AddField(
            model_name="music",
            name="spotify_link",
            field=models.TextField(default="link"),
        ),
    ]
