# Generated by Django 5.1.3 on 2025-04-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="alunos/fotos/"),
        ),
        migrations.AddField(
            model_name="docente",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="docentes/fotos/"),
        ),
    ]
