# Generated by Django 5.1.3 on 2025-04-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_aluno_foto_docente_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="disciplina",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projeto",
                to="portfolio.disciplina",
            ),
        ),
    ]
