# Generated by Django 5.1.3 on 2025-04-26 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_projeto_disciplina"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="data_criacao",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
