# Generated by Django 5.1.3 on 2025-04-26 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_projeto_data_criacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="link_projeto",
            field=models.URLField(
                blank=True, verbose_name="Link to Project on Itch.io"
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="alunos",
            field=models.ManyToManyField(blank=True, to="portfolio.aluno"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="data_criacao",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="desafios",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="disciplina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portfolio.disciplina"
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
