# Generated by Django 5.1.3 on 2025-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_projeto_link_projeto_alter_projeto_alunos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnologia",
            name="site_link",
            field=models.URLField(blank=True),
        ),
    ]
