# Generated by Django 5.1.3 on 2025-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="link",
            field=models.TextField(default="link"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comentario",
            field=models.TextField(default="comentário"),
        ),
    ]
