# Generated by Django 5.1.3 on 2025-03-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_comment_link_alter_comment_comentario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="link",
        ),
    ]
